name: ♿️ A11Y CI with Axe Core

on: [push]

jobs:
  Axe-CLI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Axe CLI
        run: npm install -g @axe-core/cli
        
      # Using the Axe Core CLI Directly
      - name: Run Axe CLI
        run: axe https://moving-motivators.cleverapps.io/ --tags wcag2a




