name: ♿️ A11Y CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]


    steps:
      # Using the Lighthouse CLI Directly
      - name: Lighthouse CLI
        run: npx lighthouse https://moving-motivators.cleverapps.io/ --chrome-flags="--no-sandbox --headless --disable-gpu" --budget-path=lighthouse-budget.json
