name: ♿️ A11Y CI with Lighthouse

on:
  workflow_dispatch:
    inputs:
      website:
        required: true
        type: string
        description: Website to audit for a11y

jobs:
  Lighthouse-CLI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Using the Lighthouse CLI Directly
      - name: Run Lighthouse CLI
        run: npx lighthouse ${{ inputs.website }} --chrome-flags="--no-sandbox --headless --disable-gpu" --budget-path=.github/workflows/lighthouse-budget.json

  Lighthouse-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Using the Lighthouse GitHub Action
      # @see https://github.com/marketplace/actions/lighthouse-ci-action
      - name: Run Lighthouse GitHub Action
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ inputs.website }} 
          budgetPath: .github/workflows/lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
