name: ♿️ A11Y CI with Pa11y

on:
  workflow_dispatch:
    inputs:
      website:
        required: true
        type: string
        description: Website to audit for a11y

jobs:
  Pa11y-CLI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Using the Pa11y CLI Directly
      - name: Run Pa11y CLI
        run: npx pa11y-ci ${{ inputs.website }}